/**
 * @fileoverview gRPC-Web generated client stub for grpc_web_demo.echo.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.0
// 	protoc              v0.0.0
// source: echo/v1/echo.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
import web from 'grpc-web';
grpc.web = web;

const proto = {};
proto.grpc_web_demo = {};
proto.grpc_web_demo.echo = {};
import v1 from './echo_pb.js';
proto.grpc_web_demo.echo.v1 = v1;

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.grpc_web_demo.echo.v1.EchoServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.grpc_web_demo.echo.v1.EchoServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.grpc_web_demo.echo.v1.EchoRequest,
 *   !proto.grpc_web_demo.echo.v1.EchoResponse>}
 */
const methodDescriptor_EchoService_Echo = new grpc.web.MethodDescriptor(
  '/grpc_web_demo.echo.v1.EchoService/Echo',
  grpc.web.MethodType.UNARY,
  proto.grpc_web_demo.echo.v1.EchoRequest,
  proto.grpc_web_demo.echo.v1.EchoResponse,
  /**
   * @param {!proto.grpc_web_demo.echo.v1.EchoRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.grpc_web_demo.echo.v1.EchoResponse.deserializeBinary
);


/**
 * @param {!proto.grpc_web_demo.echo.v1.EchoRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.grpc_web_demo.echo.v1.EchoResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.grpc_web_demo.echo.v1.EchoResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.grpc_web_demo.echo.v1.EchoServiceClient.prototype.echo =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/grpc_web_demo.echo.v1.EchoService/Echo',
      request,
      metadata || {},
      methodDescriptor_EchoService_Echo,
      callback);
};


/**
 * @param {!proto.grpc_web_demo.echo.v1.EchoRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.grpc_web_demo.echo.v1.EchoResponse>}
 *     Promise that resolves to the response
 */
proto.grpc_web_demo.echo.v1.EchoServicePromiseClient.prototype.echo =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/grpc_web_demo.echo.v1.EchoService/Echo',
      request,
      metadata || {},
      methodDescriptor_EchoService_Echo);
};


export default proto.grpc_web_demo.echo.v1;

